/* SHA-384 and ECDSA over P-384, against the elliptic-curve chain Libera
 * actually served (REQUIREMENTS.md 5.10, 5.22). The vectors in
 * ec384vectors.h are generated by tools/gen_ec384_vectors.py, which
 * verifies each one with the cryptography package before printing it,
 * so anything failing here is this client's arithmetic and not the
 * fixture's.
 *
 * The family's rule is that the host proves the arithmetic and the
 * machine measures it: nothing of P-384 goes near the MEGA65 until
 * every check below passes. */
#include <stdio.h>
#include <string.h>
#include "crypto/sha384.h"
#include "crypto/p384.h"
#include "ec384vectors.h"

static int checks, failed;
#define CHECK(cond, what) do { checks++; if (!(cond)) { failed++; printf("FAIL line %d: %s\n", __LINE__, what); } } while (0)

/* FIPS 180-4's own example, so SHA-384 is proved apart from the curve. */
static void sha384_vectors(void)
{
  static const uint8_t want_abc[48] = {
    0xcb, 0x00, 0x75, 0x3f, 0x45, 0xa3, 0x5e, 0x8b, 0xb5, 0xa0, 0x3d, 0x69,
    0x9a, 0xc6, 0x50, 0x07, 0x27, 0x2c, 0x32, 0xab, 0x0e, 0xde, 0xd1, 0x63,
    0x1a, 0x8b, 0x60, 0x5a, 0x43, 0xff, 0x5b, 0xed, 0x80, 0x86, 0x07, 0x2b,
    0xa1, 0xe7, 0xcc, 0x23, 0x58, 0xba, 0xec, 0xa1, 0x34, 0xc8, 0x25, 0xa7
  };
  /* the empty string, the other end of the padding path */
  static const uint8_t want_empty[48] = {
    0x38, 0xb0, 0x60, 0xa7, 0x51, 0xac, 0x96, 0x38, 0x4c, 0xd9, 0x32, 0x7e,
    0xb1, 0xb1, 0xe3, 0x6a, 0x21, 0xfd, 0xb7, 0x11, 0x14, 0xbe, 0x07, 0x43,
    0x4c, 0x0c, 0xc7, 0xbf, 0x63, 0xf6, 0xe1, 0xda, 0x27, 0x4e, 0xde, 0xbf,
    0xe7, 0x6f, 0x65, 0xfb, 0xd5, 0x1a, 0xd2, 0xf1, 0x48, 0x98, 0xb9, 0x5b
  };
  uint8_t out[48];
  uint8_t long_in[200];
  sha512_ctx c;
  unsigned i;

  sha384((const uint8_t *)"abc", 3, out);
  CHECK(!memcmp(out, want_abc, 48), "SHA-384(\"abc\") is FIPS 180-4's digest");
  sha384((const uint8_t *)"", 0, out);
  CHECK(!memcmp(out, want_empty, 48), "SHA-384(\"\") is the known digest");

  /* fed in pieces, which is how a certificate's TBS arrives */
  sha384_init(&c);
  sha384_update(&c, (const uint8_t *)"a", 1);
  sha384_update(&c, (const uint8_t *)"b", 1);
  sha384_update(&c, (const uint8_t *)"c", 1);
  sha384_final(&c, out);
  CHECK(!memcmp(out, want_abc, 48), "and the same in three pieces as in one");

  /* past a block boundary: 200 bytes is one 128-byte block and a tail,
   * split at 100 so the split is not where the block boundary is */
  {
    uint8_t whole[48];
    for (i = 0; i < sizeof long_in; i++) long_in[i] = (uint8_t)i;
    sha384(long_in, sizeof long_in, whole);
    sha384_init(&c);
    sha384_update(&c, long_in, 100);
    sha384_update(&c, long_in + 100, sizeof long_in - 100);
    sha384_final(&c, out);
    CHECK(!memcmp(out, whole, 48), "200 bytes split across a block boundary hash alike");
  }
}

int main(void)
{
  uint8_t bad[96];
  int i;

  printf("SHA-384, then P-384 over Libera's elliptic-curve chain:\n");
  sha384_vectors();

  for (i = 0; i < EC384_LINKS; i++) {
    char msg[160];
    snprintf(msg, sizeof msg, "%s verifies", ec384_link[i].what);
    CHECK(p384_verify(ec384_link[i].pub, ec384_link[i].hash, ec384_link[i].r, ec384_link[i].s), msg);
  }

  /* One link, bent four ways: each must be refused. The first link is
   * the leaf under its intermediate, the one a forger would attack. */
  {
    uint8_t h[48], r[48], s[48];
    memcpy(h, ec384_link[0].hash, 48);
    memcpy(r, ec384_link[0].r, 48);
    memcpy(s, ec384_link[0].s, 48);
    memcpy(bad, ec384_link[0].pub, 96);

    h[20] ^= 1;
    CHECK(!p384_verify(ec384_link[0].pub, h, r, s), "one flipped bit in the digest fails");
    h[20] ^= 1;

    r[10] ^= 1;
    CHECK(!p384_verify(ec384_link[0].pub, h, r, s), "one flipped bit in r fails");
    r[10] ^= 1;

    s[47] ^= 1;
    CHECK(!p384_verify(ec384_link[0].pub, h, r, s), "one flipped bit in s fails");
    s[47] ^= 1;

    bad[0] ^= 1;
    CHECK(!p384_verify(bad, h, r, s), "a public key that is not on the curve is refused");

    memset(r, 0, 48);
    CHECK(!p384_verify(ec384_link[0].pub, h, r, ec384_link[0].s), "r = 0 is refused");
    memset(s, 0, 48);
    CHECK(!p384_verify(ec384_link[0].pub, h, ec384_link[0].r, s), "s = 0 is refused");

    /* the second link's signature against the first link's key: a real
     * signature, a real key, the wrong pairing */
    if (EC384_LINKS > 1)
      CHECK(!p384_verify(ec384_link[0].pub, ec384_link[1].hash, ec384_link[1].r, ec384_link[1].s),
            "a real signature under the wrong key is refused");

    /* and the untouched link still passes afterwards */
    CHECK(p384_verify(ec384_link[0].pub, ec384_link[0].hash, ec384_link[0].r, ec384_link[0].s),
          "the untouched link still verifies");
  }

  printf("%d checks, %d failed\n", checks, failed);
  return failed != 0;
}
