/* The trust anchors this client carries, and nothing more.
 *
 * Decision 2: a root key or two, verified to, rather than the server's
 * key pinned. Let's Encrypt rotates every 60 to 90 days, so pinning the
 * server's key would report a change at every renewal, which is a false
 * alarm on a schedule and teaches the user to accept blindly.
 *
 * What is carried is the SHA-256 of each anchor's SubjectPublicKeyInfo,
 * not its modulus: both target networks send the cross-signed ISRG Root
 * YR in their chain (5.5), so the client verifies every signature up the
 * chain and then checks the top certificate's key against these. 32
 * bytes an anchor instead of 512, and no weaker for it.
 *
 * roots.c is generated by tools/gen_roots.py from the fixtures in
 * tests/certs and is committed.
 */
#ifndef ROOTS_H
#define ROOTS_H

#include <stdint.h>

#define ROOTS_COUNT 2

extern const uint8_t roots_spki[ROOTS_COUNT][32];
extern const char *const roots_name[ROOTS_COUNT];

/* The anchor's index for this SubjectPublicKeyInfo hash, or ROOTS_COUNT
 * if it is not one we carry. */
uint8_t roots_index(const uint8_t hash[32]);

#endif
