#!/usr/bin/env python3
"""Generates src/tls/roots.c: the trust anchors this client carries.

    python3 tools/gen_roots.py > src/tls/roots.c

Decision 2 (REQUIREMENTS.md section 2) is to carry a root key or two and
verify the chain to it, rather than pinning the server's key: Libera and
OFTC use Let's Encrypt, whose keys rotate every 60 to 90 days, so pinning
would report a changed key at every renewal.

What is carried is the SHA-256 of each anchor's SubjectPublicKeyInfo,
not its modulus. Both networks *send* the cross-signed ISRG Root YR in
their chain (5.5), so the client verifies every signature up the chain
and then checks that the top certificate's key is one of these. That is
32 bytes an anchor instead of 512, and it is exactly as strong: an
attacker cannot produce a certificate whose SPKI hashes to one of these
without the matching private key, and the link below it still has to
verify under that key.

The anchors come from the captured fixtures rather than from a bundle:
  tests/certs/libera_2.der       ISRG Root YR, as Libera and OFTC send it
  tests/certs/isrg_root_x1.der   ISRG Root X1, for a server that chains
                                 straight to it instead
"""
import hashlib
import sys
from pathlib import Path

try:
    from cryptography import x509
    from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
except ImportError:
    sys.exit("this tool needs the cryptography package: pip install cryptography")

ROOT = Path(__file__).resolve().parent.parent

# (file, the name shown on screen when a session verifies to it)
ANCHORS = [
    ("tests/certs/libera_2.der", "ISRG Root YR"),
    ("tests/certs/isrg_root_x1.der", "ISRG Root X1"),
]


def spki_hash(der: bytes) -> bytes:
    cert = x509.load_der_x509_certificate(der)
    spki = cert.public_key().public_bytes(Encoding.DER, PublicFormat.SubjectPublicKeyInfo)
    return hashlib.sha256(spki).digest()


def main():
    rows = []
    for path, name in ANCHORS:
        der = (ROOT / path).read_bytes()
        cert = x509.load_der_x509_certificate(der)
        subject = cert.subject.rfc4514_string()
        rows.append((name, spki_hash(der), subject, path))

    print("/* Generated by tools/gen_roots.py -- do not edit.")
    print(" * The SHA-256 of each carried anchor's SubjectPublicKeyInfo.")
    print(" * See the tool's docstring for why a hash and not a modulus. */")
    print('#include "roots.h"\n')
    print(f"const uint8_t roots_spki[ROOTS_COUNT][32] = {{")
    for name, h, subject, path in rows:
        print(f"  /* {name}: {subject} */")
        print("  {", end="")
        print(", ".join(f"0x{b:02x}" for b in h[:16]) + ",")
        print("   " + ", ".join(f"0x{b:02x}" for b in h[16:]) + " },")
    print("};\n")
    print("const char *const roots_name[ROOTS_COUNT] = {")
    for name, _, _, _ in rows:
        print(f'  "{name}",')
    print("};")

    print(f"\n/* {len(rows)} anchors, {32 * len(rows)} bytes of table */", file=sys.stderr)
    for name, h, subject, path in rows:
        print(f"   {name:16s} {h.hex()[:32]}...  from {path}", file=sys.stderr)
    if len(rows) != 2:
        print("NOTE: roots.h defines ROOTS_COUNT as 2; update it", file=sys.stderr)


if __name__ == "__main__":
    main()
