#!/usr/bin/env python3
"""tests/ec384vectors.h, from the elliptic-curve chain Libera actually
served (tests/certs/libera_ec_*.der, REQUIREMENTS.md 5.10).

For every link of that chain it emits what verifying it needs: the
child's TBSCertificate hashed with SHA-384, the issuer's public point as
X then Y, and the signature's r and s, each 48 bytes big-endian. Every
vector is verified here with the cryptography package before it is
printed, so a failure in the C is the C's (the family's rule: the host
proves the arithmetic, the machine measures it).

    python3 tools/gen_ec384_vectors.py > tests/ec384vectors.h

Needs the cryptography package, as tools/gen_roots.py does.
"""
import hashlib
import sys
from pathlib import Path

try:
    from cryptography import x509
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
except ImportError:
    sys.exit("this needs the cryptography package: pip install cryptography")

ROOT = Path(__file__).resolve().parent.parent
CERTS = ROOT / "tests" / "certs"
# the chain as served: leaf, YE2, Root YE, and ISRG Root X2 (which X1
# cross-signs with RSA, so that last link is not one of these)
CHAIN = ["libera_ec_0", "libera_ec_1", "libera_ec_2", "libera_ec_3"]


def be48(v: int) -> bytes:
    return v.to_bytes(48, "big")


def rows(name: str, data: bytes) -> str:
    out = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        out.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 12]) + ",")
    out.append("};")
    return "\n".join(out)


def main() -> int:
    certs = []
    for name in CHAIN:
        p = CERTS / f"{name}.der"
        if not p.is_file():
            sys.exit(f"{p} not found")
        certs.append((name, x509.load_der_x509_certificate(p.read_bytes())))

    print("/* generated by tools/gen_ec384_vectors.py: the links of the")
    print(" * elliptic-curve chain Libera served, each one verified with the")
    print(" * cryptography package before it was printed. Do not edit. */")
    print("#ifndef EC384VECTORS_H\n#define EC384VECTORS_H\n#include <stdint.h>\n")

    links = []
    for i in range(len(CHAIN) - 1):
        child_name, child = certs[i]
        issuer_name, issuer = certs[i + 1]
        pub = issuer.public_key()
        if not isinstance(pub, ec.EllipticCurvePublicKey) or pub.curve.name != "secp384r1":
            sys.exit(f"{issuer_name}: not a P-384 key, so this link is not ours to emit")
        if child.signature_algorithm_oid._name != "ecdsa-with-SHA384":
            sys.exit(f"{child_name}: signed with {child.signature_algorithm_oid._name}, not ecdsa-with-SHA384")

        # the proof, before anything is printed: the real signature over
        # the real TBS under the real key
        pub.verify(child.signature, child.tbs_certificate_bytes, ec.ECDSA(child.signature_hash_algorithm))

        r, s = decode_dss_signature(child.signature)
        numbers = pub.public_numbers()
        tag = f"link{i}"
        print(f"/* {child_name} signed by {issuer_name}:")
        print(f" *   subject {child.subject.rfc4514_string()}")
        print(f" *   issuer  {issuer.subject.rfc4514_string()} */")
        print(rows(f"{tag}_hash", hashlib.sha384(child.tbs_certificate_bytes).digest()))
        print(rows(f"{tag}_pub", be48(numbers.x) + be48(numbers.y)))
        print(rows(f"{tag}_r", be48(r)))
        print(rows(f"{tag}_s", be48(s)))
        print()
        links.append(tag)

    print(f"#define EC384_LINKS {len(links)}")
    print("static const struct { const uint8_t *hash, *pub, *r, *s; const char *what; } ec384_link[EC384_LINKS] = {")
    for i, tag in enumerate(links):
        print(f"  {{ {tag}_hash, {tag}_pub, {tag}_r, {tag}_s, \"{CHAIN[i]} under {CHAIN[i + 1]}\" }},")
    print("};\n\n#endif")
    return 0


if __name__ == "__main__":
    sys.exit(main())
